modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "${mod_issue_tracker}"
license = "${mod_license}"

[[mods]]
    modId = "${mod_id}"
    version = "${mod_version}"
    displayName = "${mod_name}"
    description = '''${mod_description}'''
    authors = "${mod_author}"
    logoFile = "icon.png"
    logoBlur = false

[[dependencies.${mod_id}]]
    modId = "forge"
    mandatory = true
    versionRange = "*"
    ordering = "NONE"
    side = "CLIENT"

[[dependencies.${mod_id}]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[${minecraft_version},)"
    ordering = "NONE"
    side = "CLIENT"